### ISSUE TITLE
Test code

### ISSUE THREAD

**Issue by JuiceTao** [PRIS-CV/DSACA#1]
Hello,where is the test code?

**Comment by xuweigogogo** [comment]
Hi, the validation phase is combined into the training code (RSOC_train_class2_CAM_DSAM.py, VisDrone_train_class8_CAM_DSAM.py).

https://github.com/PRIS-CV/DSACA/blob/6dd16208e134a4a78c554de73d6612c77f69bb4c/VisDrone_train_class8_CAM_DSAM.py#L162

**Comment by llzhuzw** [comment]
hello,I didn't find the part of the RSOC dataset that you organized. I have organized one myself, but I'm not sure if it's correct. Could you check if the number of images at each stage is a problem?I'm looking forward to your reply as well!!
<img width="113" alt="RSOC_2" src="https://github.com/user-attachments/assets/c80c1a22-c2ab-4c52-862a-967e63da18f9">

**Comment by llzhuzw** [comment]
Hello,I couldn't find the part where you organized the RSOC dataset, so I organized a version by myself. But I'm not sure if it's correct. Could you please check if the number of images in each phase is correct?Thanks!
<img width="113" alt="RSOC_2" src="https://github.com/user-attachments/assets/751e8864-3991-4fbf-bb82-43586820fb01">

**Comment by xuweigogogo** [comment]
> Hello,I couldn't find the part where you organized the RSOC dataset, so I organized a version by myself. But I'm not sure if it's correct. Could you please check if the number of images in each phase is correct?Thanks! <img alt="RSOC_2" width="113" src="https://private-user-images.githubusercontent.com/147921184/369905035-751e8864-3991-4fbf-bb82-43586820fb01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxMDAxMDgsIm5iZiI6MTcyNzA5OTgwOCwicGF0aCI6Ii8xNDc5MjExODQvMzY5OTA1MDM1LTc1MWU4ODY0LTM5OTEtNGZiZi1iYjgyLTQzNTg2ODIwZmIwMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyM1QxMzU2NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZjU5OTQ5MjU4ZmY5N2RmZjA5ODQyZDhjNjAwOGI5NDIyY2U5YWJhNDk4MjJkNDY5ODk4YzUyNjM1Yzg1MmY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.SW9cnjcIZdbp4w3A4cj7hNN336-dJDN9DZnxvgdV2LA">

Thanks for your attention! However, for some reason (as time passed), I can not analyze the original organized RSOC dataset right now. How about sending the organized dataset to my email? I would check this dataset by looking through the images contained in it.

xuwei2838@foxmail.com

**Comment by llzhuzw** [comment]
> > Hello,I couldn't find the part where you organized the RSOC dataset, so I organized a version by myself. But I'm not sure if it's correct. Could you please check if the number of images in each phase is correct?Thanks! <img alt="RSOC_2" width="113" src="https://private-user-images.githubusercontent.com/147921184/369905035-751e8864-3991-4fbf-bb82-43586820fb01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxMDAxMDgsIm5iZiI6MTcyNzA5OTgwOCwicGF0aCI6Ii8xNDc5MjExODQvMzY5OTA1MDM1LTc1MWU4ODY0LTM5OTEtNGZiZi1iYjgyLTQzNTg2ODIwZmIwMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyM1QxMzU2NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZjU5OTQ5MjU4ZmY5N2RmZjA5ODQyZDhjNjAwOGI5NDIyY2U5YWJhNDk4MjJkNDY5ODk4YzUyNjM1Yzg1MmY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.SW9cnjcIZdbp4w3A4cj7hNN336-dJDN9DZnxvgdV2LA">
> 
> Thanks for your attention! However, for some reason (as time passed), I can not analyze the original organized RSOC dataset right now. How about sending the organized dataset to my email? I would check this dataset by looking through the images contained in it.
> 
> [xuwei2838@foxmail.com](mailto:xuwei2838@foxmail.com)

OK

**Comment by xuweigogogo** [comment]
> > > Hello,I couldn't find the part where you organized the RSOC dataset, so I organized a version by myself. But I'm not sure if it's correct. Could you please check if the number of images in each phase is correct?Thanks! <img alt="RSOC_2" width="113" src="https://private-user-images.githubusercontent.com/147921184/369905035-751e8864-3991-4fbf-bb82-43586820fb01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxMDAxMDgsIm5iZiI6MTcyNzA5OTgwOCwicGF0aCI6Ii8xNDc5MjExODQvMzY5OTA1MDM1LTc1MWU4ODY0LTM5OTEtNGZiZi1iYjgyLTQzNTg2ODIwZmIwMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyM1QxMzU2NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZjU5OTQ5MjU4ZmY5N2RmZjA5ODQyZDhjNjAwOGI5NDIyY2U5YWJhNDk4MjJkNDY5ODk4YzUyNjM1Yzg1MmY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.SW9cnjcIZdbp4w3A4cj7hNN336-dJDN9DZnxvgdV2LA">
> > 
> > 
> > Thanks for your attention! However, for some reason (as time passed), I can not analyze the original organized RSOC dataset right now. How about sending the organized dataset to my email? I would check this dataset by looking through the images contained in it.
> > [xuwei2838@foxmail.com](mailto:xuwei2838@foxmail.com)
> 
> OK

After looking through the dataset you provided, I think you have employed the correct procedures to organize it. The essential procedures are two steps:
Step 1: combine the small- and large-vehicle images into a single set;
Step 2: combine the annotations of small and large vehicles in the same image.

In my opinion, the dataset you provided is correct. You can check if there are missed details for further confirmation.

Thanks for your efforts.
