### ISSUE TITLE
Train problem

### ISSUE THREAD

**Issue by Cy-26** [PRIS-CV/DSACA#2]
Hello, thank you for your contributions. Based on your original code, I have modified the dataset to fit my own, which is a two-class classification task similar to your classification of large and small vehicles. During training, I noticed that when calculating the loss function using the following code:

loss2 = lamda * criterion[1](mask_plane_pre, mask_plane_map.long()) + lamda * criterion[1](mask_ship_pre, mask_ship_map.long())

The value of loss2 remains constant at 1.3376 throughout the training process. As a result, during testing, the predicted mask is all zeros, leading to failures in classification and counting. I compared the ground truth and predicted results using the feature_test function from your source code, as shown in the attached image. I would like to ask what might be causing this issue and what steps I should take to troubleshoot and correct it.
Thank you!
![1](https://github.com/user-attachments/assets/04af458d-8807-404e-b089-8a7e9a1aa7f4)

**Comment by xuweigogogo** [comment]
> Hello, thank you for your contributions. Based on your original code, I have modified the dataset to fit my own, which is a two-class classification task similar to your classification of large and small vehicles. During training, I noticed that when calculating the loss function using the following code:
> 
> loss2 = lamda * criterion[1](mask_plane_pre, mask_plane_map.long()) + lamda * criterion[1](mask_ship_pre, mask_ship_map.long())
> 
> The value of loss2 remains constant at 1.3376 throughout the training process. As a result, during testing, the predicted mask is all zeros, leading to failures in classification and counting. I compared the ground truth and predicted results using the feature_test function from your source code, as shown in the attached image. I would like to ask what might be causing this issue and what steps I should take to troubleshoot and correct it. Thank you! ![1](https://private-user-images.githubusercontent.com/65476218/376044749-04af458d-8807-404e-b089-8a7e9a1aa7f4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MzIxMDYsIm5iZiI6MTcyODgzMTgwNiwicGF0aCI6Ii82NTQ3NjIxOC8zNzYwNDQ3NDktMDRhZjQ1OGQtODgwNy00MDRlLWIwODktOGE3ZTlhMWFhN2Y0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEzVDE1MDMyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0ZDJhMDc1ZDA0MTU1ZGQ3MDk1ODJlNzMxMzMzNjVlYjVhMjE1YmJlMjEwZGI0OWJiYjYyNjIyNjIzNTk4N2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gAlQoeyMMvLa4tQTmFwnMyFkOLxxkaMI40ZRjwxditc)

Thanks for your detailed information! In my opinion, the problem may be that the mask branch has not been converged. In my experiments, the mask branch takes about 100 epochs to converge. You can visualize the predicted density maps before multiplying them with the predicted masks for checking.

**Comment by llzhuzw** [comment]
Hello, I encountered a similar issue. Like you, I am running on the RSOC subset, but after 200 epochs, it still hasn't converged. What could be the possible problem? Are the parameter settings exactly the same as in the published code?

**Comment by llzhuzw** [comment]
> Hello, thank you for your contributions. Based on your original code, I have modified the dataset to fit my own, which is a two-class classification task similar to your classification of large and small vehicles. During training, I noticed that when calculating the loss function using the following code:
> 
> loss2 = lamda * criterion[1](mask_plane_pre, mask_plane_map.long()) + lamda * criterion[1](mask_ship_pre, mask_ship_map.long())
> 
> The value of loss2 remains constant at 1.3376 throughout the training process. As a result, during testing, the predicted mask is all zeros, leading to failures in classification and counting. I compared the ground truth and predicted results using the feature_test function from your source code, as shown in the attached image. I would like to ask what might be causing this issue and what steps I should take to troubleshoot and correct it. Thank you! ![1](https://private-user-images.githubusercontent.com/65476218/376044749-04af458d-8807-404e-b089-8a7e9a1aa7f4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNzc1NzEsIm5iZiI6MTcyOTA3NzI3MSwicGF0aCI6Ii82NTQ3NjIxOC8zNzYwNDQ3NDktMDRhZjQ1OGQtODgwNy00MDRlLWIwODktOGE3ZTlhMWFhN2Y0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDExMTQzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1ZWU1YjJiMWFkYWFlOGQ2MmIyMjQ2NTRlODZjN2VjY2ZiNzFhZDFhZTI0NTQzYTlhYjc1YzQ5ZTg1MDhhY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qevUuIQ_ZbINyUnEegkM7AeA3yhfd9NYguE7fWW5tYo)

Did you manage to solve the issue? How did you solve it? I'm encountering a similar problem which mask_pre is all zeros.Thanks.

**Comment by Cy-26** [comment]
> Hello, I encountered a similar issue. Like you, I am running on the RSOC subset, but after 200 epochs, it still hasn't converged. What could be the possible problem? Are the parameter settings exactly the same as in the published code?

Yes, my parameter settings are the same as those in the provided code. Based on the author's recommendation, I trained my dataset for over 300 epochs before the mask_pre started fitting the data in the training set. Currently, I have trained for 1000 epochs, and most of the training data shows good results. However, the validation set still performs poorly, and training is ongoing. As shown in the image, this is the result of one image during one of the training processes
![微信图片_20241018110603](https://github.com/user-attachments/assets/5ec77f38-00a6-4da6-b365-9993a548a413)
![微信图片_20241018110628](https://github.com/user-attachments/assets/db87eb7a-d13e-43e6-9240-6b24aaf42e7e)

**Comment by llzhuzw** [comment]
> > Hello, I encountered a similar issue. Like you, I am running on the RSOC subset, but after 200 epochs, it still hasn't converged. What could be the possible problem? Are the parameter settings exactly the same as in the published code?
> 
> Yes, my parameter settings are the same as those in the provided code. Based on the author's recommendation, I trained my dataset for over 300 epochs before the mask_pre started fitting the data in the training set. Currently, I have trained for 1000 epochs, and most of the training data shows good results. However, the validation set still performs poorly, and training is ongoing. As shown in the image, this is the result of one image during one of the training processes ![微信图片_20241018110603](https://private-user-images.githubusercontent.com/65476218/377705689-5ec77f38-00a6-4da6-b365-9993a548a413.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0MzAzMDksIm5iZiI6MTcyOTQzMDAwOSwicGF0aCI6Ii82NTQ3NjIxOC8zNzc3MDU2ODktNWVjNzdmMzgtMDBhNi00ZGE2LWIzNjUtOTk5M2E1NDhhNDEzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIwVDEzMTMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlOTI1ZGUzMzliMmQ1Yzg1Mjk5NTZhZTRkZWMwOGY2OGJiNTM0ZGZiNDE1MTEzN2IxNWJkOWFlYzM0ZmJhYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rDVtPeAsvm_H21OnmsExeTXSec2LG0Dvf8x7ykSU-s0) ![微信图片_20241018110628](https://private-user-images.githubusercontent.com/65476218/377705759-db87eb7a-d13e-43e6-9240-6b24aaf42e7e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0MzAzMDksIm5iZiI6MTcyOTQzMDAwOSwicGF0aCI6Ii82NTQ3NjIxOC8zNzc3MDU3NTktZGI4N2ViN2EtZDEzZS00M2U2LTkyNDAtNmIyNGFhZjQyZTdlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIwVDEzMTMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkYjk4YjY4MjE4ZTJiZDllZmVmYTc5MjUzZTRhYTExZTU0NWI1ZmQ4NjQ2YzU0OWU1NzkwZjdhMjAwZGVhYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.v9JQr1mjgJqBAN_EjUKU3iw36cUbiau9TvURGGPRwic)

Thank you for your response. I'm pleased with the classification results for the small vehicle category, but the large vehicle category is not converging at all. May I have your wechat? I would like to communicate with you in a more convenient manner.

**Comment by Cy-26** [comment]
> > > Hello, I encountered a similar issue. Like you, I am running on the RSOC subset, but after 200 epochs, it still hasn't converged. What could be the possible problem? Are the parameter settings exactly the same as in the published code?
> > 
> > 
> > Yes, my parameter settings are the same as those in the provided code. Based on the author's recommendation, I trained my dataset for over 300 epochs before the mask_pre started fitting the data in the training set. Currently, I have trained for 1000 epochs, and most of the training data shows good results. However, the validation set still performs poorly, and training is ongoing. As shown in the image, this is the result of one image during one of the training processes ![微信图片_20241018110603](https://private-user-images.githubusercontent.com/65476218/377705689-5ec77f38-00a6-4da6-b365-9993a548a413.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0MzAzMDksIm5iZiI6MTcyOTQzMDAwOSwicGF0aCI6Ii82NTQ3NjIxOC8zNzc3MDU2ODktNWVjNzdmMzgtMDBhNi00ZGE2LWIzNjUtOTk5M2E1NDhhNDEzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIwVDEzMTMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlOTI1ZGUzMzliMmQ1Yzg1Mjk5NTZhZTRkZWMwOGY2OGJiNTM0ZGZiNDE1MTEzN2IxNWJkOWFlYzM0ZmJhYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rDVtPeAsvm_H21OnmsExeTXSec2LG0Dvf8x7ykSU-s0) ![微信图片_20241018110628](https://private-user-images.githubusercontent.com/65476218/377705759-db87eb7a-d13e-43e6-9240-6b24aaf42e7e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0MzAzMDksIm5iZiI6MTcyOTQzMDAwOSwicGF0aCI6Ii82NTQ3NjIxOC8zNzc3MDU3NTktZGI4N2ViN2EtZDEzZS00M2U2LTkyNDAtNmIyNGFhZjQyZTdlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIwVDEzMTMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkYjk4YjY4MjE4ZTJiZDllZmVmYTc5MjUzZTRhYTExZTU0NWI1ZmQ4NjQ2YzU0OWU1NzkwZjdhMjAwZGVhYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.v9JQr1mjgJqBAN_EjUKU3iw36cUbiau9TvURGGPRwic)
> 
> Thank you for your response. I'm pleased with the classification results for the small vehicle category, but the large vehicle category is not converging at all. May I have your wechat? I would like to communicate with you in a more convenient manner.

Hello, I found an issue with the true labels in my images, which caused good performance on the training set but poor classification and counting on the test set. After making corrections, I'm now facing a situation similar to yours. The model can classify and detect one category, but the mask for the other category fails to fit and remains entirely zero. I'd like to ask if you have any solutions or ideas for addressing this issue. Thank you!

**Comment by llzhuzw** [comment]
> > > > Hello, I encountered a similar issue. Like you, I am running on the RSOC subset, but after 200 epochs, it still hasn't converged. What could be the possible problem? Are the parameter settings exactly the same as in the published code?
> > > 
> > > 
> > > Yes, my parameter settings are the same as those in the provided code. Based on the author's recommendation, I trained my dataset for over 300 epochs before the mask_pre started fitting the data in the training set. Currently, I have trained for 1000 epochs, and most of the training data shows good results. However, the validation set still performs poorly, and training is ongoing. As shown in the image, this is the result of one image during one of the training processes ![微信图片_20241018110603](https://private-user-images.githubusercontent.com/65476218/377705689-5ec77f38-00a6-4da6-b365-9993a548a413.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0MzAzMDksIm5iZiI6MTcyOTQzMDAwOSwicGF0aCI6Ii82NTQ3NjIxOC8zNzc3MDU2ODktNWVjNzdmMzgtMDBhNi00ZGE2LWIzNjUtOTk5M2E1NDhhNDEzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIwVDEzMTMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlOTI1ZGUzMzliMmQ1Yzg1Mjk5NTZhZTRkZWMwOGY2OGJiNTM0ZGZiNDE1MTEzN2IxNWJkOWFlYzM0ZmJhYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rDVtPeAsvm_H21OnmsExeTXSec2LG0Dvf8x7ykSU-s0) ![微信图片_20241018110628](https://private-user-images.githubusercontent.com/65476218/377705759-db87eb7a-d13e-43e6-9240-6b24aaf42e7e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0MzAzMDksIm5iZiI6MTcyOTQzMDAwOSwicGF0aCI6Ii82NTQ3NjIxOC8zNzc3MDU3NTktZGI4N2ViN2EtZDEzZS00M2U2LTkyNDAtNmIyNGFhZjQyZTdlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIwVDEzMTMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkYjk4YjY4MjE4ZTJiZDllZmVmYTc5MjUzZTRhYTExZTU0NWI1ZmQ4NjQ2YzU0OWU1NzkwZjdhMjAwZGVhYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.v9JQr1mjgJqBAN_EjUKU3iw36cUbiau9TvURGGPRwic)
> > 
> > 
> > Thank you for your response. I'm pleased with the classification results for the small vehicle category, but the large vehicle category is not converging at all. May I have your wechat? I would like to communicate with you in a more convenient manner.
> 
> Hello, I found an issue with the true labels in my images, which caused good performance on the training set but poor classification and counting on the test set. After making corrections, I'm now facing a situation similar to yours. The model can classify and detect one category, but the mask for the other category fails to fit and remains entirely zero. I'd like to ask if you have any solutions or ideas for addressing this issue. Thank you!

Hello, I haven't been able to resolve this issue yet. Would it be possible for you to provide a contact method for more immediate communication? The current mode of communication has a high latency.

**Comment by Cy-26** [comment]
> > > > > Hello, I encountered a similar issue. Like you, I am running on the RSOC subset, but after 200 epochs, it still hasn't converged. What could be the possible problem? Are the parameter settings exactly the same as in the published code?
> > > > 
> > > > 
> > > > Yes, my parameter settings are the same as those in the provided code. Based on the author's recommendation, I trained my dataset for over 300 epochs before the mask_pre started fitting the data in the training set. Currently, I have trained for 1000 epochs, and most of the training data shows good results. However, the validation set still performs poorly, and training is ongoing. As shown in the image, this is the result of one image during one of the training processes ![微信图片_20241018110603](https://private-user-images.githubusercontent.com/65476218/377705689-5ec77f38-00a6-4da6-b365-9993a548a413.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0MzAzMDksIm5iZiI6MTcyOTQzMDAwOSwicGF0aCI6Ii82NTQ3NjIxOC8zNzc3MDU2ODktNWVjNzdmMzgtMDBhNi00ZGE2LWIzNjUtOTk5M2E1NDhhNDEzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIwVDEzMTMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlOTI1ZGUzMzliMmQ1Yzg1Mjk5NTZhZTRkZWMwOGY2OGJiNTM0ZGZiNDE1MTEzN2IxNWJkOWFlYzM0ZmJhYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rDVtPeAsvm_H21OnmsExeTXSec2LG0Dvf8x7ykSU-s0) ![微信图片_20241018110628](https://private-user-images.githubusercontent.com/65476218/377705759-db87eb7a-d13e-43e6-9240-6b24aaf42e7e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0MzAzMDksIm5iZiI6MTcyOTQzMDAwOSwicGF0aCI6Ii82NTQ3NjIxOC8zNzc3MDU3NTktZGI4N2ViN2EtZDEzZS00M2U2LTkyNDAtNmIyNGFhZjQyZTdlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIwVDEzMTMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkYjk4YjY4MjE4ZTJiZDllZmVmYTc5MjUzZTRhYTExZTU0NWI1ZmQ4NjQ2YzU0OWU1NzkwZjdhMjAwZGVhYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.v9JQr1mjgJqBAN_EjUKU3iw36cUbiau9TvURGGPRwic)
> > > 
> > > 
> > > Thank you for your response. I'm pleased with the classification results for the small vehicle category, but the large vehicle category is not converging at all. May I have your wechat? I would like to communicate with you in a more convenient manner.
> > 
> > 
> > Hello, I found an issue with the true labels in my images, which caused good performance on the training set but poor classification and counting on the test set. After making corrections, I'm now facing a situation similar to yours. The model can classify and detect one category, but the mask for the other category fails to fit and remains entirely zero. I'd like to ask if you have any solutions or ideas for addressing this issue. Thank you!
> 
> Hello, I haven't been able to resolve this issue yet. Would it be possible for you to provide a contact method for more immediate communication? The current mode of communication has a high latency.

My WeChat ID is: cy_hhh26. Please feel free to add me when convenient so we can communicate and collaborate more easily. Additionally, regarding the issue I previously mentioned with one of the class masks being entirely zero, I discovered it was due to the classification branch in the network not fully converging. During my training, the problem was resolved after 800 epochs, and at the current epoch of 900, the counting results for both classes are significantly improved. Below is a comparison between the ground truth and the prediction results on an image from my personal dataset during the training process.
![result](https://github.com/user-attachments/assets/8e0111cc-bcd2-4111-8b48-fa06c4b77a2b)
